import { Business, PhysicalCaptureRecord, CommunityDemandSignal, CommunityMission, UserReview } from "@/types";

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: "biz-1",
    name: "Salon Nova Style Biryogo",
    nameRw: "Salo Nova Style Biryogo",
    category: "salon_barber",
    categoryDisplay: "Salons & Barbers",
    categoryDisplayRw: "Za Salo & Kogosha",
    description: "Specialized in modern African haircuts, fade designs, dreadlocks retwisting, beard grooming, and hair wash.",
    descriptionRw: "Bamenyereye kogosha imisatsi y'ubwoko bwose, gufunga dreadlocks, gusukura ubwanwa, no gukaraba mu mutwe.",
    phone: "+250788123456",
    whatsapp: "250788123456",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Biryogo",
      community: "Biryogo Car-Free Zone",
      addressNote: "Opposite Green Tea Corner, 2nd door on the right",
      coordinates: { lat: -1.9774, lng: 30.0482 },
    },
    verificationStatus: "HIGH_CONFIDENCE",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-12",
      locationConfirmed: true,
      ownerConfirmed: true,
      communityConfirmationsCount: 14,
      recentActivityDate: "2026-09-14",
    },
    photos: [
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "08:00", close: "21:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "08:00", close: "21:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "08:00", close: "21:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "08:00", close: "21:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "08:00", close: "22:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "07:30", close: "22:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "09:00", close: "21:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "LOW",
    products: [
      {
        id: "p-101",
        businessId: "biz-1",
        name: "Standard Haircut (Fade / Normal)",
        nameRw: "Kogosha Bisanzwe",
        description: "Includes clipper styling and alcohol disinfectant spray",
        price: 2000,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Haircut",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.98,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-12",
      },
      {
        id: "p-102",
        businessId: "biz-1",
        name: "Beard Trim & Hot Towel Treatment",
        nameRw: "Kogosha Ubwanwa no Kwisiga",
        price: 1000,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Grooming",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.95,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-12",
      },
      {
        id: "p-103",
        businessId: "biz-1",
        name: "Dreadlocks Washing & Retwisting",
        nameRw: "Gufunga no Koza Dreadlocks",
        price: 8000,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Haircare",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.92,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-12",
      },
    ],
    viewsCount: 142,
    contactClicksCount: 38,
    searchAppearancesCount: 215,
    claimedByUserId: "user-owner-1",
    createdByAgentId: "agent-1",
    featuredOffer: {
      title: "Student Discount: 1500 Frw haircut on Tuesdays",
      titleRw: "Gabanirizwa: Kogosha 1500 Frw ku banyeshuri kuwa Kabiri",
      discount: "25% OFF",
      validUntil: "2026-10-31",
    },
    createdAt: "2026-08-10",
    updatedAt: "2026-09-12",
  },
  {
    id: "biz-2",
    name: "Atelier de Couture Umwiza",
    nameRw: "Atelier y'Abadozi Umwiza",
    category: "tailor_crafts",
    categoryDisplay: "Tailors & Craftsmen",
    categoryDisplayRw: "Abadozi & Ubukorikori",
    description: "Expert tailors creating customized Kitenge garments, African suits, school uniforms, and swift emergency zipper / hem repairs.",
    descriptionRw: "Abadozi b'inararibonye badoda ibitenge bigezweho, amakositimu, imyenda y'ishuri, no gusana imyenda yacitse vuba na bwangu.",
    phone: "+250788234567",
    whatsapp: "250788234567",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Biryogo",
      community: "Cosmos",
      addressNote: "Next to Cosmos Pharmacie, green gate",
      coordinates: { lat: -1.9810, lng: 30.0460 },
    },
    verificationStatus: "AGENT_VERIFIED",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-10",
      locationConfirmed: true,
      ownerConfirmed: false,
      communityConfirmationsCount: 8,
      recentActivityDate: "2026-09-13",
    },
    photos: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "08:00", close: "19:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "08:00", close: "19:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "08:00", close: "19:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "08:00", close: "19:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "08:00", close: "19:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "08:00", close: "20:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "10:00", close: "16:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "MODERATE",
    products: [
      {
        id: "p-201",
        businessId: "biz-2",
        name: "Kitenge Modern Dress Tailoring",
        nameRw: "Kudoda Ikanzu y'Igitenge",
        price: 14000,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Tailoring",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.96,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-10",
      },
      {
        id: "p-202",
        businessId: "biz-2",
        name: "Zipper Replacement / Emergency Hem",
        nameRw: "Guteraho Umushumi w'Iserire (Fermeture)",
        price: 1500,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Alterations",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-10",
      },
      {
        id: "p-203",
        businessId: "biz-2",
        name: "Men's Traditional Shirt Tailoring",
        nameRw: "Kudoda Ishati y'Igitenge y'Abagabo",
        price: 10000,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Tailoring",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.94,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-10",
      },
    ],
    viewsCount: 98,
    contactClicksCount: 22,
    searchAppearancesCount: 160,
    createdByAgentId: "agent-1",
    createdAt: "2026-08-15",
    updatedAt: "2026-09-10",
  },
  {
    id: "biz-3",
    name: "Cosmos Tech & Phone Clinic",
    nameRw: "Ibyuma & Gusana Telefone Cosmos",
    category: "phone_electronics",
    categoryDisplay: "Phone & Electronics Repair",
    categoryDisplayRw: "Gusana Telefone & Ibikoresho",
    description: "Fast diagnostics and micro-soldering for Android and iPhones. Broken screens, charging pins, speaker issues, and battery replacement.",
    descriptionRw: "Gusana no gusimbuza ecran za telefone zamenetse, guhindura ama bateri, n'ibindi byuma bya telefone mu buryo bwizewe.",
    phone: "+250788345678",
    whatsapp: "250788345678",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Biryogo",
      community: "Cosmos",
      addressNote: "Beside Cosmos Commercial Center, Shop #4",
      coordinates: { lat: -1.9815, lng: 30.0465 },
    },
    verificationStatus: "COMMUNITY_VERIFIED",
    verificationDetails: {
      agentVerified: true,
      agentName: "Aline Uwase",
      agentVerifiedAt: "2026-09-08",
      locationConfirmed: true,
      ownerConfirmed: true,
      communityConfirmationsCount: 19,
      recentActivityDate: "2026-09-15",
    },
    photos: [
      "https://images.unsplash.com/photo-1597740985671-2a8a3b80532e?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1597740985671-2a8a3b80532e?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "08:30", close: "20:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "08:30", close: "20:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "08:30", close: "20:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "08:30", close: "20:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "08:30", close: "20:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "08:30", close: "20:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "13:00", close: "18:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "MODERATE",
    products: [
      {
        id: "p-301",
        businessId: "biz-3",
        name: "Type-C / Micro Charging Port Replacement",
        nameRw: "Guhindura Umunwa wo Gucagingiraho",
        price: 4500,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Hardware Repair",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.98,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-08",
      },
      {
        id: "p-302",
        businessId: "biz-3",
        name: "Original Android Screen Replacement (Tecno/Infinix/Samsung)",
        nameRw: "Gusimbuza Ecran y'Umwimerere",
        price: 18000,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Screens",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.93,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-08",
      },
      {
        id: "p-303",
        businessId: "biz-3",
        name: "Tempered Glass Screen Protector + Fitting",
        nameRw: "Ikirahure cyo Kurinda Ecran (Protection)",
        price: 2000,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Accessories",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-08",
      },
    ],
    viewsCount: 230,
    contactClicksCount: 64,
    searchAppearancesCount: 310,
    claimedByUserId: "user-owner-3",
    createdByAgentId: "agent-2",
    createdAt: "2026-08-01",
    updatedAt: "2026-09-08",
  },
  {
    id: "biz-4",
    name: "Kivugiza Fresh Milk & Chapati Corner",
    nameRw: "Amata Meza & Chapati Kivugiza",
    category: "food_restaurant",
    categoryDisplay: "Food & Milk Bars",
    categoryDisplayRw: "Ibiryo & Amamata",
    description: "Authentic Rwandan milk bar serving fresh boiled Nyagatare milk, traditional spiced tea (icyayi cy'amazi), hot layered chapatis, and fresh eggs.",
    descriptionRw: "Akabari k'amata gatanga amata meza yatetse aturuka i Nyagatare, icyayi cy'amazi, chapati zishyushye, n'amagi atetse.",
    phone: "+250788456789",
    whatsapp: "250788456789",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Mumena",
      community: "Kivugiza",
      addressNote: "Kivugiza Junction near Mumena Primary Gate",
      coordinates: { lat: -1.9920, lng: 30.0480 },
    },
    verificationStatus: "HIGH_CONFIDENCE",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-11",
      locationConfirmed: true,
      ownerConfirmed: true,
      communityConfirmationsCount: 26,
      recentActivityDate: "2026-09-14",
    },
    photos: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "06:00", close: "21:30", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "06:00", close: "21:30", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "06:00", close: "21:30", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "06:00", close: "21:30", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "06:00", close: "22:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "06:00", close: "22:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "06:30", close: "21:30", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "LOW",
    products: [
      {
        id: "p-401",
        businessId: "biz-4",
        name: "Fresh Boiled Cow Milk (1 Cup)",
        nameRw: "Igikombe cy'Amata y'Inka Yatetse",
        price: 500,
        currency: "RWF",
        unit: "cup",
        isAvailable: true,
        category: "Beverages",
        extractedFrom: "MENU",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-11",
      },
      {
        id: "p-402",
        businessId: "biz-4",
        name: "Hot Layered Chapati",
        nameRw: "Chapati Ishyushye y'Urupapuro",
        price: 300,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Snacks",
        extractedFrom: "MENU",
        confidenceScore: 0.98,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-11",
      },
      {
        id: "p-403",
        businessId: "biz-4",
        name: "Spiced African Ginger Tea (Icyayi cy'Amazi)",
        nameRw: "Icyayi cy'Amazi kirimo Tangawizi",
        price: 300,
        currency: "RWF",
        unit: "cup",
        isAvailable: true,
        category: "Beverages",
        extractedFrom: "MENU",
        confidenceScore: 0.97,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-11",
      },
    ],
    viewsCount: 180,
    contactClicksCount: 45,
    searchAppearancesCount: 290,
    claimedByUserId: "user-owner-4",
    createdByAgentId: "agent-1",
    featuredOffer: {
      title: "Breakfast Combo: Milk + 2 Chapatis for 1000 Frw",
      titleRw: "Ifunguro rya Mugitondo: Amata + Chapati 2 kuri 1000 Frw",
      discount: "Save 100 Frw",
      validUntil: "2026-11-30",
    },
    createdAt: "2026-08-05",
    updatedAt: "2026-09-11",
  },
  {
    id: "biz-5",
    name: "Tapi Rouge Moto & Auto Spares",
    nameRw: "Ibyuma bya Moto n'Imodoka Tapi Rouge",
    category: "mechanic_repair",
    categoryDisplay: "Mechanics & Spares",
    categoryDisplayRw: "Abakanishi & Ibyuma by'Ibinyabiziga",
    description: "Motorcycle maintenance, brake replacement, chain tightening, spark plugs, high grade lubricant oil, and puncture vulcanizing.",
    descriptionRw: "Gusana moto, guhindura amaplake ya feri, amavuta meza ya moteri, no gutera udupece ku mapine yatobotse.",
    phone: "+250788567890",
    whatsapp: "250788567890",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Rwezamenyo",
      community: "Tapi Rouge",
      addressNote: "Behind Tapi Rouge Basketball pitch",
      coordinates: { lat: -1.9840, lng: 30.0450 },
    },
    verificationStatus: "AGENT_VERIFIED",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-09",
      locationConfirmed: true,
      ownerConfirmed: false,
      communityConfirmationsCount: 11,
      recentActivityDate: "2026-09-12",
    },
    photos: [
      "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "07:30", close: "19:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "07:30", close: "19:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "07:30", close: "19:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "07:30", close: "19:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "07:30", close: "19:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "07:30", close: "19:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "08:00", close: "14:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "MODERATE",
    products: [
      {
        id: "p-501",
        businessId: "biz-5",
        name: "Motorcycle Engine Oil (Total 4T 1L)",
        nameRw: "Amavuta ya Moto (Total 4T Litro 1)",
        price: 5500,
        currency: "RWF",
        unit: "bottle",
        isAvailable: true,
        category: "Fluids",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.98,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-09",
      },
      {
        id: "p-502",
        businessId: "biz-5",
        name: "Brake Pads Replacement + Labor",
        nameRw: "Gushyiramo Amaplake ya Feri Mashya",
        price: 3500,
        currency: "RWF",
        unit: "service",
        isAvailable: true,
        category: "Brakes",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.95,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-09",
      },
    ],
    viewsCount: 112,
    contactClicksCount: 31,
    searchAppearancesCount: 174,
    createdByAgentId: "agent-1",
    createdAt: "2026-08-20",
    updatedAt: "2026-09-09",
  },
  {
    id: "biz-6",
    name: "Alimentation Générale Tapi Rouge",
    nameRw: "Iduka ry'Ibiribwa Tapi Rouge",
    category: "shop_retail",
    categoryDisplay: "Local Shops & Groceries",
    categoryDisplayRw: "Amaduka & Ibiribwa",
    description: "Neighborhood convenience shop offering quality staples: Kinazi cassava flour, Gorillaz rice, cooking sunflower oil, sugar, and Rwandan tea leaves.",
    descriptionRw: "Iduka ricuruza ibiribwa by'ubwoko bwose: ifu ya Kinazi, umuceri wa Gorillaz, amavuta yo guteka, isukari n'amajyani y'u Rwanda.",
    phone: "+250788678901",
    whatsapp: "250788678901",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Rwezamenyo",
      community: "Tapi Rouge",
      addressNote: "Main road junction facing Pharmacy la Grâce",
      coordinates: { lat: -1.9845, lng: 30.0455 },
    },
    verificationStatus: "BUSINESS_VERIFIED",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-07",
      locationConfirmed: true,
      ownerConfirmed: true,
      communityConfirmationsCount: 15,
      recentActivityDate: "2026-09-14",
    },
    photos: [
      "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "07:00", close: "22:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "07:00", close: "22:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "07:00", close: "22:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "07:00", close: "22:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "07:00", close: "22:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "07:00", close: "22:30", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "08:00", close: "21:30", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "LOW",
    products: [
      {
        id: "p-601",
        businessId: "biz-6",
        name: "Gorillaz Super Basmati Rice (1kg)",
        nameRw: "Umuceri wa Gorillaz (Ikiro 1)",
        price: 1800,
        currency: "RWF",
        unit: "kg",
        isAvailable: true,
        category: "Groceries",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-07",
      },
      {
        id: "p-602",
        businessId: "biz-6",
        name: "Pure Sunflower Oil (1 Liter bottle)",
        nameRw: "Amavuta yo Guteka y'Ibihwagari (Litro 1)",
        price: 3200,
        currency: "RWF",
        unit: "liter",
        isAvailable: true,
        category: "Cooking",
        extractedFrom: "RECEIPT",
        confidenceScore: 0.96,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-07",
      },
    ],
    viewsCount: 165,
    contactClicksCount: 39,
    searchAppearancesCount: 220,
    claimedByUserId: "user-owner-6",
    createdByAgentId: "agent-1",
    createdAt: "2026-08-18",
    updatedAt: "2026-09-07",
  },
  {
    id: "biz-7",
    name: "Nyamirambo Artisan & Cultural Weavers",
    nameRw: "Abanyabukorikori b'i Nyamirambo",
    category: "art_culture",
    categoryDisplay: "Art & Culture Centers",
    categoryDisplayRw: "Ubuhanzi & Umuco",
    description: "Women cooperative crafting authentic Agaseke baskets, sisal wall hangings, woven earrings, and traditional Rwandan home decors.",
    descriptionRw: "Koperative y'abagore baboha uduseke tw'umwimerere, imitako yo ku rukuta, impeta n'ibikoresho by'umuco nyarwanda.",
    phone: "+250788789012",
    whatsapp: "250788789012",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Rwezamenyo",
      community: "Maison des Jeunes",
      addressNote: "Inside Maison des Jeunes Cultural Courtyard",
      coordinates: { lat: -1.9825, lng: 30.0440 },
    },
    verificationStatus: "HIGH_CONFIDENCE",
    verificationDetails: {
      agentVerified: true,
      agentName: "Aline Uwase",
      agentVerifiedAt: "2026-09-05",
      locationConfirmed: true,
      ownerConfirmed: true,
      communityConfirmationsCount: 22,
      recentActivityDate: "2026-09-14",
    },
    photos: [
      "https://images.unsplash.com/photo-1590736969955-71cc94801759?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1590736969955-71cc94801759?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "09:00", close: "18:00", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "09:00", close: "18:00", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "09:00", close: "18:00", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "09:00", close: "18:00", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "09:00", close: "18:00", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "09:00", close: "18:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "11:00", close: "17:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "MODERATE",
    products: [
      {
        id: "p-701",
        businessId: "biz-7",
        name: "Handmade Peace Basket (Agaseke k'Amahoro)",
        nameRw: "Agaseke k'Amahoro Kaboshywe n'Intoki",
        price: 8000,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Handicrafts",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-05",
      },
      {
        id: "p-702",
        businessId: "biz-7",
        name: "Woven Sisal Wall Hanging Disc (30cm)",
        nameRw: "Umutako wo ku Rukuta Uboshywe (Sisal)",
        price: 12000,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Home Decor",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.97,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-05",
      },
    ],
    viewsCount: 204,
    contactClicksCount: 52,
    searchAppearancesCount: 280,
    claimedByUserId: "user-owner-7",
    createdByAgentId: "agent-2",
    createdAt: "2026-08-01",
    updatedAt: "2026-09-05",
  },
  {
    id: "biz-8",
    name: "Kuri 40 Fresh Fruit & Green Veggies",
    nameRw: "Imboga n'Imbuto Nshya Kuri 40",
    category: "agriculture_produce",
    categoryDisplay: "Fresh Produce & Farmers",
    categoryDisplayRw: "Umusaruro w'Ubuhinzi & Imboga",
    description: "Daily direct delivery from Musanze and Bugesera: fresh avocados, sweet mangoes, green dodo, broccoli, carrots, and ripe bananas.",
    descriptionRw: "Umusaruro w'umwimerere uturuka i Musanze n'i Bugesera: avoka nziza, imyembe, dodo, karoti n'ibitoki bishya.",
    phone: "+250788890123",
    whatsapp: "250788890123",
    location: {
      country: "Rwanda",
      province: "Kigali City",
      district: "Nyarugenge",
      sector: "Nyamirambo",
      cell: "Rwezamenyo",
      community: "Mirongo Ine",
      addressNote: "Kuri 40 bus stop, next to Equity Bank ATM",
      coordinates: { lat: -1.9870, lng: 30.0425 },
    },
    verificationStatus: "AGENT_VERIFIED",
    verificationDetails: {
      agentVerified: true,
      agentName: "Emmanuel Hakizimana",
      agentVerifiedAt: "2026-09-13",
      locationConfirmed: true,
      ownerConfirmed: false,
      communityConfirmationsCount: 16,
      recentActivityDate: "2026-09-15",
    },
    photos: [
      "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop&q=60",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=60",
    ],
    coverImage: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800&auto=format&fit=crop&q=60",
    openingHours: [
      { day: "Monday", dayRw: "Kuwa Mbere", open: "06:30", close: "20:30", isClosed: false },
      { day: "Tuesday", dayRw: "Kuwa Kabiri", open: "06:30", close: "20:30", isClosed: false },
      { day: "Wednesday", dayRw: "Kuwa Gatatu", open: "06:30", close: "20:30", isClosed: false },
      { day: "Thursday", dayRw: "Kuwa Kane", open: "06:30", close: "20:30", isClosed: false },
      { day: "Friday", dayRw: "Kuwa Gatanu", open: "06:30", close: "20:30", isClosed: false },
      { day: "Saturday", dayRw: "Kuwa Gatandatu", open: "06:30", close: "21:00", isClosed: false },
      { day: "Sunday", dayRw: "Ku Cyumweru", open: "07:00", close: "20:00", isClosed: false },
    ],
    isOpenNow: true,
    priceRange: "LOW",
    products: [
      {
        id: "p-801",
        businessId: "biz-8",
        name: "Large Ripe Hass Avocado (Piece)",
        nameRw: "Avoka Nini Yeze Neza",
        price: 300,
        currency: "RWF",
        unit: "piece",
        isAvailable: true,
        category: "Fruits",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.99,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-13",
      },
      {
        id: "p-802",
        businessId: "biz-8",
        name: "Fresh Local Dodo / Amaranth (Bundle)",
        nameRw: "Umushyitsi w'Imboga za Dodo",
        price: 200,
        currency: "RWF",
        unit: "bundle",
        isAvailable: true,
        category: "Vegetables",
        extractedFrom: "PRICE_BOARD",
        confidenceScore: 0.98,
        verifiedByAgent: true,
        lastVerifiedAt: "2026-09-13",
      },
    ],
    viewsCount: 139,
    contactClicksCount: 34,
    searchAppearancesCount: 198,
    createdByAgentId: "agent-1",
    createdAt: "2026-08-25",
    updatedAt: "2026-09-13",
  },
];

export const INITIAL_CAPTURES: PhysicalCaptureRecord[] = [
  {
    id: "cap-1",
    businessId: "biz-3",
    businessName: "Cosmos Tech & Phone Clinic",
    agentId: "agent-1",
    agentName: "Emmanuel Hakizimana",
    documentType: "RECEIPT",
    imageUrl: "https://images.unsplash.com/photo-1554415707-9e4466aef152?w=800&auto=format&fit=crop&q=60",
    rawOcrText: `COSMOS TECH REPAIR CLINIC\nTIN: 104829104\nNYAMIRAMBO - BIRYOGO\nTEL: 0788345678\nDATE: 2026-09-08 14:22\n\n1. Type-C Charging Port       4500 RWF\n2. Tecno Screen Fit           18000 RWF\n3. Glass Protector             2000 RWF\n\nTOTAL: 24500 RWF\nCASH RECEIVED: 25000 RWF\nCHANGE: 500 RWF\n\n*THANK YOU FOR VISITING*`,
    extractedMerchant: "COSMOS TECH REPAIR CLINIC",
    extractedDate: "2026-09-08",
    extractedItems: [
      { id: "ci-1", name: "Type-C Charging Port", price: 4500, quantity: 1, category: "Hardware Repair", confidence: 0.98 },
      { id: "ci-2", name: "Tecno Screen Fit", price: 18000, quantity: 1, category: "Screens", confidence: 0.93 },
      { id: "ci-3", name: "Glass Protector", price: 2000, quantity: 1, category: "Accessories", confidence: 0.99 },
    ],
    extractedTotal: 24500,
    currency: "RWF",
    status: "VERIFIED",
    sanitized: true,
    uploadedAt: "2026-09-08T14:30:00Z",
    verifiedAt: "2026-09-08T14:35:00Z",
  },
  {
    id: "cap-2",
    businessId: "biz-4",
    businessName: "Kivugiza Fresh Milk & Chapati Corner",
    agentId: "agent-1",
    agentName: "Emmanuel Hakizimana",
    documentType: "MENU",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=60",
    rawOcrText: `AMATA MEZA YA KIVUGIZA\nIKIRAHO CY'AMATA: 500 FRW\nCHAPATI Y'AMAFARANGA: 300 FRW\nICYAYI CY'AMAZI: 300 FRW\nIGI RITETSE: 300 FRW\nSAMBUSA: 200 FRW`,
    extractedMerchant: "AMATA MEZA YA KIVUGIZA",
    extractedDate: "2026-09-11",
    extractedItems: [
      { id: "ci-4", name: "Ikiraho cy'Amata (Fresh Boiled Milk)", price: 500, quantity: 1, category: "Beverages", confidence: 0.99 },
      { id: "ci-5", name: "Chapati Ishyushye", price: 300, quantity: 1, category: "Snacks", confidence: 0.98 },
      { id: "ci-6", name: "Icyayi cy'Amazi", price: 300, quantity: 1, category: "Beverages", confidence: 0.97 },
      { id: "ci-7", name: "Igi Ritetse", price: 300, quantity: 1, category: "Snacks", confidence: 0.95 },
    ],
    extractedTotal: 1400,
    currency: "RWF",
    status: "VERIFIED",
    sanitized: true,
    uploadedAt: "2026-09-11T09:10:00Z",
    verifiedAt: "2026-09-11T09:15:00Z",
  },
];

export const INITIAL_DEMAND_SIGNALS: CommunityDemandSignal[] = [
  {
    id: "dem-1",
    sector: "Nyamirambo",
    cell: "Biryogo",
    category: "phone_electronics",
    categoryRw: "Gusana Telefone & Ibikoresho",
    queryTerm: "Phone screen replacement",
    queryTermRw: "Gusana ecran ya telefone",
    searchCount: 38,
    activeBusinessesCount: 2,
    opportunityScore: "VERY_HIGH",
    description: "High local search traffic for iPhone and Samsung screen fixes in Biryogo, with only 2 verified workshops available.",
    descriptionRw: "Abaturage benshi bari gushaka aho basanira ecran za iPhone na Samsung i Biryogo, mu gihe hari amaduka 2 gusa yemejwe.",
    updatedAt: "2026-09-14",
  },
  {
    id: "dem-2",
    sector: "Nyamirambo",
    cell: "Mumena",
    category: "services",
    categoryRw: "Izindi Serivisi",
    queryTerm: "Emergency electrician near Stadium",
    queryTermRw: "Umunyamashanyarazi wihuta hafi ya Sitade",
    searchCount: 29,
    activeBusinessesCount: 1,
    opportunityScore: "VERY_HIGH",
    description: "Residents frequently search for domestic electrical troubleshooting; huge unmet gap for certified local electricians.",
    descriptionRw: "Abaturage bakunda gushaka abanyamashanyarazi bo mu ngo; hari icyuho kinini cy'abanyamwuga babizobereyemo.",
    updatedAt: "2026-09-15",
  },
  {
    id: "dem-3",
    sector: "Nyamirambo",
    cell: "Rwezamenyo",
    category: "tailor_crafts",
    categoryRw: "Abadozi & Ubukorikori",
    queryTerm: "Express Kitenge Suit Tailoring",
    queryTermRw: "Kudoda ikositimu y'igitenge byihuse",
    searchCount: 25,
    activeBusinessesCount: 2,
    opportunityScore: "HIGH",
    description: "Surge in weekend requests for tailored event outfits delivered in under 48 hours.",
    descriptionRw: "Ubwiyongere bw'abashaka amakanzu n'imyenda y'ibirori bidodwa mu minsi ibiri gusa.",
    updatedAt: "2026-09-13",
  },
  {
    id: "dem-4",
    sector: "Nyamirambo",
    cell: "Biryogo",
    category: "food_restaurant",
    categoryRw: "Ibiryo & Amamata",
    queryTerm: "Organic Honey and Ginger Tea Delivery",
    queryTermRw: "Ubwuki bw'umwimerere n'icyayi cy'amazi",
    searchCount: 19,
    activeBusinessesCount: 3,
    opportunityScore: "MODERATE",
    description: "Growing evening appetite for natural tea blends and pure forest honey jars in Car-Free Zone.",
    descriptionRw: "Icyifuzo cy'abashaka ubwuki bw'amashyamba n'amajyani y'umwimerere mu mugoroba.",
    updatedAt: "2026-09-12",
  },
];

export const INITIAL_MISSIONS: CommunityMission[] = [
  {
    id: "mis-1",
    title: "Discover a Hidden Tailor in Biryogo",
    titleRw: "Vumbura Umudozi Wihishe i Biryogo",
    description: "Find an unlisted neighborhood tailor, snap their storefront sign or sample garments, and record their exact location.",
    descriptionRw: "Shakisha umudozi utarandikwa mu gace kawe, ufate ifoto y'icyapa cye cyangwa imyenda adoda, maze wandike aho akorera.",
    targetArea: "Biryogo",
    pointsReward: 50,
    badgeReward: "Neighborhood Explorer",
    category: "DISCOVER",
  },
  {
    id: "mis-2",
    title: "Verify Opening Hours at Cosmos Junction",
    titleRw: "Suzuma Amasaha yo Gufungura Kuri Cosmos",
    description: "Visit 2 shops around Cosmos roundabout and confirm whether their displayed opening times match reality.",
    descriptionRw: "Sura amaduka 2 akorera kuri Cosmos wemeze niba amasaha agaragazwa ku muryango ahura n'uko bafungura.",
    targetArea: "Cosmos",
    pointsReward: 30,
    badgeReward: "Community Helper",
    category: "VERIFY",
  },
  {
    id: "mis-3",
    title: "Capture a Physical Price Board",
    titleRw: "Fata Ifoto y'Ikibaho cy'Ibiciro",
    description: "Use the Agent capture tool to photograph a salon board, milk bar menu, or grocery chalk price list.",
    descriptionRw: "Koresha uburyo bwa capture ufate ifoto y'ikibaho cy'ibiciro cya salo, akabari k'amata cyangwa iduka.",
    targetArea: "Tapi Rouge & 40",
    pointsReward: 75,
    badgeReward: "Local Scout",
    category: "UPDATE",
  },
  {
    id: "mis-4",
    title: "Recommend a Trustworthy Mechanic",
    titleRw: "Ranga Umukanishi Wizewe",
    description: "Submit a positive review and location confirmation for an automotive or motorcycle repairer in Mumena.",
    descriptionRw: "Tanga ubuhamya bwiza kandi wemeze aho umukanishi wa moto cyangwa imodoka akorera i Mumena.",
    targetArea: "Mumena",
    pointsReward: 40,
    badgeReward: "Community Champion",
    category: "RECOMMEND",
  },
];

export const INITIAL_REVIEWS: UserReview[] = [
  {
    id: "rev-1",
    businessId: "biz-1",
    userName: "Jean-Paul Mugisha",
    userRole: "CUSTOMER",
    rating: 5,
    comment: "Best fade in Nyamirambo! Extremely clean equipment and Emmanuel the agent verified their location accurately.",
    commentRw: "Kogosha neza cyane muri Nyamirambo! Ibikoresho byisukuye kandi byemejwe n'umukozi wacu Emmanuel.",
    verifiedVisit: true,
    createdAt: "2026-09-13",
  },
  {
    id: "rev-2",
    businessId: "biz-3",
    userName: "Chantal Mukamana",
    userRole: "CUSTOMER",
    rating: 5,
    comment: "They fixed my phone screen in 40 minutes while I had tea at Kivugiza milk bar. Honest pricing!",
    commentRw: "Bansaniye ecran ya telefone mu minota 40 gusa nkiri kunywa amata muri Kivugiza. Ibiciro bidahenze kandi byizewe!",
    verifiedVisit: true,
    createdAt: "2026-09-10",
  },
];
